// Product categories and names for QuickCompare API
module.exports = {
    // Rice and related products
    rice: [
        "Sunlite Organic Sonamasuri White Rice",
        "Pahari Roots White Sticky Rice from Meghalaya",
        "Daawat Basmati Rice",
        "India Gate Basmati Rice",
        "Fortune Biryani Special Basmati Rice",
        "Fortune Hamesha Mini Dubar Basmati Rice",
        "Pansari Mahak",
        "Fortune Rozana Basmati Rice",
        "Fortune Everyday Basmati Rice",
        "Daawat Biryani Basmati Rice",
        "India Gate Basmati Rice Classic Long Grain Basmati",
        "Charminar Long Grain Rice Pouch",
        "24 Mantra Organic Sona Masoori Polished Raw Rice Chawal",
        "Supreme Harvest Sona Masoori Raw Rice",
        "India Gate Classic Premium Basmati Rice",
        "India Gate Super Basmati Rice",
        "Daawat Pulav Basmati Rice",
        "India Gate Rozzana Basmati Rice",
        "India Gate Mogra Basmati Rice",
        "Daawat Sehat Mini Mogra Basmati Rice",
        "India Gate Basmati Rice Everyday Basmati",
        "India Gate Basmati Rice Daily Premium Basmati",
        "CROWN Daily Rozana Basmati Rice",
        "India Gate Mini Mogra 2 Basmati Rice",
        "Daawat Quick Cooking Brown Basmati Rice",
        "Aravalli Classic Sella / Parboiled Basmati Rice",
        "India Gate Regular Choice Basmati Rice Medium",
        "Daawat Super Long Grain Basmati Rice",
        "Pansari Tasty Basmati Rice",
        "India Gate Special Brown Rice",
        "Pansari Signature Basmati Long Grain Biryani Rice",
        "India Gate Gobindobhog Aged & Raw Rice",
        "Pansari Khana Basmati Long Grain Biryani Rice , Chawal",
        "CROWN Deluxe Pulav Basmati Rice",
        "Daawat Traditional Basmati Rice",
        "Safe Harvest Ponni Boiled Rice",
        "Supreme Harvest Idly Rice",
        "921 Rozana Broken Basmati Rice",
        "Tilda Long Grain Rice",
        "CROWN Diet Rice Basmati Rice",
        "CROWN Opal Super Basmati Rice",
        "Mtr Rice Idli Mix",
        "Pahari Roots Black Rice",
        "Rehaan 1121 Classic Extra Long Grain Biryani Basmati Rice 1kg",
        "921 Lajawab Pulav Basmati Rice",
        "921 Lajawab Mini Mungra Basmati Rice",
        "Aravalli Parmal Raw Rice",
        "Safe Harvest Pesticide Free Sona Masoori Raw Rice 12 Months",
        "24 Mantra Sona Masoori Raw Rice Polished",
        "Aravalli Classic Basmati Rice",
        "Safe Harvest Pesticide Free Sona Masoori Unpolished Brown Rice",
        "organic tattva Sonamasuri Rice Brown",
        "921 Lajawab Super Mungra Basmati Rice",
        "921 Everyday Long Grain Rice",
        "921 Classic Xxxl Extra Long Grain Biryani 1121 Basmati Rice",
        "Supreme Harvest Long Grain Rice",
        "Pansari Royal Basmati Long Grain Biryani Chawal",
        "organic tattva Biryani Basmati Rice",
        "Supreme Harvest Rozana Basmati Rice",
        "Daawat Heritage Super Dubar Basmati Rice Pouch",
        "Daawat Dubar Basmati Rice",
        "Pansari Mahotsav Umang Basmati Long Grain Rice, Chawal",
        "Kohinoor Lucknowi Biryani Kit With Pepsi",
        "Rehaan 1121 Classic Extra Long Grain Biryani Basmati Rice",
        "Kohinoor Mogra Basmati Rice",
        "Just Organik Organic Basmati Rice",
        "Maya Basmati Mini Mogra Rice",
        "Safe Harvest Sona Masuri Brown Rice",
        "24 Mantra Organic Gluten Free Sonamasuri Brown Rice",
        "921 Sushi Rice",
        "Tilda Brown Basmati Rice",
        "Daawat Red Rice",
        "Pahari Roots Red Rice from Meghalaya",
        "Maya Red Rice",
        "Maya Dubar Rice"
    ],
    
    // Flour and related products
    flour: [
        "Aashirvaad Select Sharbati Atta",
        "Fortune Chakki Fresh Atta",
        "organic tattva Whole Wheat Flour Chakki Atta",
        "Aashirvaad Organic Whole Wheat Atta",
        "Aashirvaad Shudh Chakki Atta",
        "Dilli Di Chakki Shudh Chakki Atta",
        "Vikram Mills Fresh Chakki Atta",
        "Aashirvaad MP Chakki Atta",
        "Pillsbury Chakki Fresh Atta",
        "Dilli Di Chakki Sharbati Wheat Atta",
        "Dilli Di Chakki Multigrain Atta",
        "Patanjali Whole Wheat Atta",
        "Ahaar Chana Flour",
        "The Better Flour Khpli Whole Wheat Atta, Low Gi, High Fibre Flour",
        "Just Organik Organic Atta",
        "Aashirvaad Besan",
        "Rajdhani Sattu",
        "Pansari Wheat Chakki Fresh Atta",
        "Supreme Harvest Whole Wheat Atta",
        "Natureland Organics Whole Wheat Flour",
        "24 Mantra Whole Wheat Atta",
        "Ahaar Chakki Fresh Atta",
        "Buy Fortune Chakki Fresh Atta 10Kg & Get Fortune Besan 500Gm Free*",
        "Dilli Di Chakki Jowar Atta",
        "Supreme Harvest Whole Wheat",
        "Dilli Di Chakki Sattu Atta",
        "24 Mantra Whole Wheat Atta Premium",
        "Amul Organic Whole Wheat Atta",
        "Fortune Chakki Fresh Atta & Fortune Soyabean Oil Pouch & Fortune Sugar Combo",
        "Aeroplane Chakki Fresh Atta",
        "Pansari Maida",
        "Aashirvaad Multigrains Atta",
        "Pillsbury Multigrain Atta",
        "organic tattva Multigrain Atta",
        "Supreme Harvest Ragi Atta",
        "Dr. Gluten Platinum Chapati Flour",
        "Pansari Soyabean Atta",
        "Dr. Gluten Multi Millet Flour",
        "Supreme Harvest Bajra Atta",
        "Ahaar Jowar Flour",
        "Dr. Gluten Low GI Diabetic Atta",
        "24 Mantra Ragi Flour",
        "Pansari Bajra Atta",
        "Natureland Organics Buckwheat Flour",
        "DiabeSmart Diabetic Sugar Care Atta",
        "Just Organik Organic Quinoa Flour",
        "Safe Harvest Pesticide Free Bajra Atta",
        "Natureship Hand roasted and stone ground desi Corn/Makai sattu",
        "Ahaar Besan",
        "Fortune Maida",
        "Rajdhani Maida",
        "Supreme Harvest Maida",
        "DSF Premium Maida",
        "Dilli Di Chakki Besan",
        "Rajdhani Besan",
        "Rajdhani Sooji",
        "Tata Sampann 100% Chana Dal Fine Besan",
        "Vikram Mills Sooji 500 g, Vikram Mills Maida 500 G",
        "Rajdhani Besan/Gram Flour",
        "Fortune Sooji",
    ],
    
    // Bread and related products
    bread: [
        "The Baker's Dozen Zero Maida Fourgrain Sourdough",
        "The Baker's Dozen Banana Walnut Cake",
        "Safe Harvest Roasted Sooji",
        "The Health Factory Multigrain Bread",
        "English Oven Zero maida Multigrain Bread",
        "The Health Factory 100% Whole Wheat Bread",
        "Mangat Ram Besan",
        "Harvest Gold",
        "Britannia 100% Whole Wheat Bread",
        "The Baker's Dozen Zero Maida Pita Bread",
        "The Baker's Dozen Zero Maida Fourgrain Sourdough + Eggoz White Herbal Feed Eggs",
        "English Oven Zero maida 100% Atta Bread",
        "The Baker's Dozen Zero Maida Banana Walnut Cake & Wagh Bakri Premium Leaf Tea Pouch",
        "The Baker's Dozen Zero Maida Bread",
        "The Baker's Dozen Zero Maida Multigrain Loaf",
        "English Oven Zero Maida 100%Whole Wheat Bread",
        "English Oven Zero Maida whole wheat",
        "The Baker'S Dozen Zero Maida Banana Walnut Cake & Choco Chip Cake",
        "The Baker's Dozen Zero Maida Ragi Loaf",
        "The Baker's Dozen Zero Maida Banana Bread | No Palm Oil | 20% Bananas & Fruit & Nut Cake | Real Fruits & Nuts l No Palm Oil",
        "Mcvitie's Hobnobs Crunchy Chocochip Cookies , 0% Maida & 36% Oats",
        "The Baker's Dozen Assorted Muffins & The Baker's Dozen Zero Maida Banana Walnut Cake",
        "The Baker's Dozen Zero Maida Baked Lavash",
        "Safe Harvest Roasted Sooji",
        "organic tattva Suji",
        "Supreme Harvest Upma Sooji",
        "24 Mantra Idly Rava",
        "Supreme Harvest Barik Rava",
        "Pansari Sooji",
        "DSF Premium Sooji",
        "KITCHEN GEMS Idli Rawa",
        "Rajdhani Mota Besan",
        "Harvest Gold Suji Rusk",
        "Mtr Rava Idli Mix",
        "Britannia Toastea Premium Bake Rusk With Goodness Of Elaichi Sooji & Wheat",
    ],
    
    // Pasta, noodles and related products
    pasta: [
        "TGF Penne Pasta",
        "ORGANIC TATTVA Masala Rava Idli Ready Mix",
        "Voylla Rava Ball Oxidized Dangle Earrings",
        "Voylla Rava Ball Statement Ring",
        "Bambino Semolina Roasted Vermicelli",
        "Mtr Masala Rava Idli",
        "Mtr Breakfast Mix",
        "Mtr Rava Dosa Mix",
        "ORGANIC TATTVA Rava Dosa Ready Mix",
        "Voylla Rava Ball Oxidized Jhumka Style Earrings",
        "DSF Premium Besan",
        "Tata Sampann Besan",
        "Fortune Besan Flour",
        "Fortune Besan",
        "Supreme Harvest Besan",
        "organic tattva Ragi Flour",
        "Pansari Ragi Atta",
        "Dilli Di Chakki Ragi Atta",
        "24 Mantra Rice Flour",
        "Supreme Harvest Kuttu Atta",
        "ORGANIC TATTVA Ragi Dosa Ready Mix",
        "Khetika Ragi Millet Dosa Batter",
        "Let's Try Ragi Kaju Pista Cookies",
        "Slurrp Farm No Added Sugar Ragi, Almond and Banana Cereal, 100% Sprouted Ragi, No Milk No Preservatives",
        "Slurrp Farm 100% Sprouted Ragi Powder, No Added Sugar, No Milk",
        "Saffola Crunchiez Ragi Chips Takatak Tomato",
        "Yoga Baby No Milk Solids, Maida & Chemicals Sprouted Ragi Powder",
        "Slurrp Farm No Added Sugar Ragi, Rice and Banana Instant Cereal with Milk, No Preservatives, No Salt",
        "Slurrp Farm No Maida No Refined Sugar Banana Oat Cookies & Slurrp Farm No Maida No Refined Sugar Choco Ragi Cookies",
        "Snackible Peri Peri Ragi Chips",
        "Cerelac Nestle Ragi Apple Baby cereal 300g | No Refined Sugar |With Protein Iron Calcium ALA",
        "Cookie Man Millet Jaggery Cookies",
        "iD Fresh Ragi Millet idly & Dosa Batter",
        "Snackible Piri Piri Ragi Chips",
        "Theobroma Ragi Crackers",
        "The Whole Truth Protein Starter Pack",
        "Slurrp Farm Strawberry Cereal, No Added Sugar Instant Cereal with Ragi, Rice and Milk",
        "TATA Soulfull Ragi Bites Choco Fills",
        "Cookie Man Sugar Free Ragi Millet Cookies",
        "Slurrp Farm No Added Sugar, No Salt Strawberry and Sprouted Ragi Cereals Trial Pack Combo",
        "Slurrp Farm No Added Sugar Instant Cereal",
        "Little Joys NutriMix 7+ milk mix",
        "The Baker's Dozen Zero Maida Baked Ragi Crackers",
        "Supreme Harvest Jowar Flour",
        "24 Mantra Jowar Flour Sorghum Flour Jonna",
        "24 Mantra Bajra Flour Pearl Millet Flour Sajjalu",
        "Aashirvaad Natures Super Foods Multi Millet Mix",
        "Supreme Harvest Rajgira Flour",
        "Deepak Premium Rice Atta",
        "Supreme Harvest Rice Flour",
        "Kitchen Gems Moong Chilka",
        "Weikfield CornFlour Amazingly Versatile Gluten Free",
        "Supreme Harvest Tapioca Flour",
        "Weikfield Corn Starch Amazingly Versatile Gluten Free",
        "24 Mantra Besan Gram Flour",
        "Borges Farfalle Durum Wheat Pasta",
        "A Natural Pasta",
        "Borges Penne Rigate Wheat Pasta",
        "Borges Durum Wheat Fusilli Pasta",
        "Bambino Macaroni Pasta Elbow",
        "Maggi Pazzta Instant Pasta Cheese Macaroni",
        "Borges Spaghetti Wheat Pasta",
        "Yu Three Cheese Pasta Instant Ready Meal",
        "Disano Spaghetti Pasta 100% Durum Wheat",
        "Del Monte Spaghetti Pasta",
        "Yu Peri Peri Pasta Instant Ready Meal",
        "Keya Fusilli Pasta 100% Durum Wheat",
        "Maggi Pazzta Instant Pasta Masala Penne",
        "Sunfeast Yippee Masala Instant Pasta",
        "Bambino Premium All Seasons Penne Pasta",
        "Amor Penne Pasta",
        "Amor Fusilli Pasta",
        "Bambino Premium All Seasons Fusilli Pasta",
        "Amor Fusilli Pasta + Arrabiata Pasta Sauce",
        "Sunfeast Yippee Creamy Corn Tricolor Pasta",
        "Red Pasta Combo",
        "Yu Peri Peri Pasta Instant Ready Meal and Yu Three Cheese Pasta Instant Ready Meal",
        "Yu Three Cheese Pasta And Yu Zingy Cheese Instant Cup Noodles",
        "Bambino All Season Premium Durum Wheat Pasta",
        "Disano Elbow Pasta 100% Durum Wheat",
        "Disano Penne Pasta 100% Durum Wheat",
        "Keya Penne Pasta 100% Durum Wheat",
        "Disano Fusilli Pasta 100% Durum Wheat",
        "Sunfeast Yippee Cheese Instant Pasta",
        "Keya Penne Rigate Pasta & Keya Spiralli Fusilli Pasta Combo",
        "TGF Spaghetti Pasta",
        "Del Monte Penne Rigate Wheat Pasta",
        "Keya Elbow Pasta 100% Durum Wheat",
        "Sunfeast Yippee Tricolor Pasta Masala",
        "TGF Fusili Pasta Pouch & Penne Pasta Pouch Combo",
        "TGF Penne Pasta Pouch & Pasta & Pizza Sauce Combo",
        "WickedGud Spaghetti Pasta & Akasa Alio Olio Pasta Sauce",
    ],
    
    // Noodles and related products
    noodles: [
        "Maggi 2",
        "Wai Wai Ready to Eat Veg Masala Flavoured Noodles Pack of 6",
        "Wai Wai Cup Noodles Veg",
        "Ching's Secret Whole Wheat Noodles, No Maida",
        "Yu Chilli Cheese Korean Ramen",
        "Masterchow Hakka Noodles",
        "Masterchow Whole Wheat Noodles",
        "MOI SOI Instant Hakka Noodles Chowmein flavour Sauce",
        "Yu Zingy Cheese Instant Cup Noodles",
        "Maggi Veg Atta Noodles",
        "Maggi Masala Instant Noodles",
        "Yu Chilli Chicken Instant Cup Noodles",
        "Masterchow Udon Noodles",
        "Top Ramen Curry Saucy Flat Noodles",
        "Wickedgud Instant Masala Cup Noodles",
        "Ching's Secret Veg Hakka Noodles",
        "Sunfeast Yippee Mood Masala Noodles Money Saver Pack",
        "Yu Jalapeno Cheese",
        "Nongshim Shin Ramyun Soup Noodles Soup",
        "Maggi Masala Cuppa Noodles",
        "Wai Wai Ready To Eat Chicken Noodles",
        "Masterchow Instant Cup Noodles",
        "Sunfeast Yippee Magic Masala Noodles",
        "Nissin Geki Hot & Spicy Korean Veg Noodles",
        "Maggi 2 Minute Noodles Special Masala",
        "Wai Wai Cup Noodles Chicken",
        "Yu High Protein Whole Wheat Noodles",
        "Nissin Geki Hot & Spicy Korean Instant Noodles Kimchi Flavor",
        "Nissin Geki Hot & Spicy Korean Chicken Flavour Noodles",
        "Tops Plain Noodles",
        "Maggi Chilly Chow Cuppa Noodles",
        "Nissin Geki Hot & Spicy Korean Instant Noodles Veg Flavour",
        "Indomie Mi Goreng Instant Noodles Fried Noodles Flavour",
        "Masterchow Whole Wheat Noodles and Masterchow Hakka Noodles Combo",
        "Nissin Cup Noodles Mazedaar Masala",
        "Maggi Masala Instant Noodles & Maggi Veg Atta Noodles",
        "Maggi Masala Instant Noodles 280 gm + Thums Up Soft Drink Bottle 750 ml",
        "Indomie Vegetable Flavour Instant Noodles",
        "Nissin Cup Noodles Spiced Chicken",
        "Nissin Cup Noodles Veggi Manchow",
        "Nissin Cup Noodles Chilli Chilli Chilli",
        "Kitchen Gems Sabudana Big",
        "Supreme Harvest Sabudana Small",
        "Deepak Premium Sabudana",
        "Jk Masale Small Sago",
        "DNV Sabudana",
        "Rajdhani Sabudana",
        "Pansari Sabudana",
        "DNV Sabudana Papad",
        "Sweet Karam Coffee Indian Masala Kerala Tapioca Chips",
        "HALDIRAM DELHI Sabudana Tikki",
        "Flavours of Calicut Authentic Tapioca Chips",
        "Mother's Recipe Sabudana Papad",
        "Sweet Karam Coffee Nendran Banana Chips & Tapioca Chips",
        "Sweet Karam Coffee Tapioca Chips",
        "Modern Kitchens Tapioca Sticks",
    ],
    
    // Dal and pulses
    pulses: [
        "Natureland Organics Chana Besan",
        "Daadi's Besan Laddoo Pure Ghee 1 Pack",
        "Being Bania Masala Besan Gatta",
        "Amul Besan Laddoo",
        "Fortune Sattu",
        "Bikano Besan Laddu",
        "TGF Besan Ghee Ladoo",
        "LAL Besan Laddoo Classic",
        "Haldiram's Besan Burfi B1G1",
        "Kaleva Til Besan Laddoo",
        "Gujrat Namkeen Gujarati Besan Papdi",
        "Buy Soyabean Oil 5ltr Jar & Get Besan 500g Free",
        "Bambino Roasted Vermicelli",
        "Bambino Premium Vermicelli",
        "TGF Roasted Vermicelli",
        "Bambino Popular Vermicelli",
        "Real Thai Rice Vermicelli",
        "Maggi Korean Spicy Cheesy Instant Cuppa Noodles",
        "Nissin Geki Cheese",
        "YOPOKKI Cheese topokki rice cake bowl",
        "YOPOKKI Hot & spicy topokki rice cake bowl",
        "SAMYANG Hot Chicken Flavour Topokki Rice Cake",
        "Yu 100% Whole Wheat Noodles 150 g and Yu Chilli Garlic Fried Rice Instant Cup",
        "Nongshim Shin Cup Noodle Soup",
        "Nongshim Kimchi Cup Noodle Soup",
        "Yu Zingy Cheese Instant Cup Noodles And Yu Chilli Chicken Instant Cup Noodles",
        "Nongshim Stir Fry With Cheese Noodle",
        "Ahaar Oat Meal Daliya",
        "Ahaar Barley Daliya",
        "Supreme Harvest Broken Wheat",
        "Rajdhani Dalia",
        "Patanjali Dalia",
        "Rajdhani Roasted Daliya",
        "Natureland Organics Wheat Dalia",
        "Ahaar Classic Daliya",
        "Ahaar Maize Daliya",
        "24 Mantra Organic Wheat Dhaliya",
        "Being Bania Multigrain Daliya Khichdi",
    ],
    
    // Cooking oils and related products
    oils: [
        "Fortune Sunlite Refined Sunflower Oil",
        "Sundrop Superlite Advanced Sunflower Oil",
        "Borges Classic Pure Olive Oil",
        "Borges Extra Virgin Olive Oil",
        "Dalda Sunflower Oil",
        "Dhara Health Refined Sunflower Oil",
        "Borges Extra Light Olive Oil",
        "Emami Healthy & Tasty Refined Sunflower Oil 900 g Pouch",
        "Sundrop Refined Sunflower Oil",
        "Emami Sunflower Oil",
        "Jivo Gold Refined Oil",
        "INDICWISDOM Wood Pressed Sunflower Oil",
        "Jivo Cold Pressed Chemical Free Sunflower Oil",
        "Just Organik Organic Sunflower Oil",
        "Pro Nature Organic Sunflower Oil",
        "24 Mantra Organic Expeller Pressed Sunflower Oil",
        "Jivika Naturals Cold Pressed Sunflower Oil",
        "Jivika Naturals Himalayan Rock Salt",
        "Jivika Naturals Cold Pressed Sesame Oil",
        "Jivika Naturals Cold Pressed Peanut Oil",
        "Natureland Organics Sunflower Oil",
        "Sundrop Superlite Advanced Sunflower Oil Saver Pack",
        "24 Mantra Organic Unrefined Safflower Oil",
        "Fortune Health Rice Bran Refined Oil Pouch",
        "Fortune Xpert Pro Immunity Oil Blend of Rice Bran & Sunflower Oil",
        "Fortune Rice Bran Health Oil",
        "Fortune Kachi Ghani Mustard Oil",
        "Saffola Gold Refined Cooking Oil Blend Of Rice Bran & Corn Oil",
        "Fortune Soya Health Refined soyabean Oil",
        "Dhara Soyabean Oil",
        "Saffola Total Refined Cooking Oil Blend Of Rice Bran & Safflower Oil",
        "Leonardo Olive Pomace Oil",
        "Anveshan Sunflower Oil",
        "organic tattva Organic Sunflower Oil Bottle",
        "Del Monte Olive Pomace Oil",
        "Fortune Rice Bran 1L & Mustard Oil 1L Pet",
        "Jivo Extra Light Edible Olive Oil Ideal for Everyday Indian Cooking",
        "Fortune Xpert Pro Sugar Conscious Oil Blend of Rice Bran & Sesame Oil",
        "Oleev Smart Vitafit Edibale Vegetable Oil",
        "Klf Tilnad Pure Gingelly/Til Oil",
        "Dalda Soyabean Oil",
        "Jivo Daily Cooking Pomace Olive Oil",
        "Fortune soya Health Refine soyabean oil",
        "Emami Refined Soyabean Oil",
        "Allegro Pomace Olive Oil",
        "Fortune Mustard 1L Pack & Soyabean Oil 1L Pet",
    ],
    
    // Ghee and butter products
    ghee: [
        "Organic India Organic Cow Ghee",
        "Amul Pure Ghee",
        "Milkfood Rich Desi Ghee",
        "Kapiva A2 Cow Desi Ghee",
        "Kapiva Organic Ghee",
        "Gowardhan Pure Cow Ghee",
        "BAROSi A2 Desi Cow Ghee",
        "Anveshan A2 Desi Cow Ghee",
        "Anveshan A2 Gir Cow Ghee",
        "PARAS Desi Ghee Tetra Pack",
        "BAROSi Cultured Cow Ghee",
        "Gowardhan Ghee Festival Pack With Lock & Seal Container Jar",
        "Patanjali Cow's Ghee",
        "Ananda Pure Ghee",
        "PARAS Desi Ghee",
        "PARAS Nandan Cow Ghee",
        "Amul Pure Ghee",
        "Patanjali Cow's Ghee Jar",
        "TRUEFARM Certified A2 Ghee Pack",
        "Aashirvaad Svasti Organic Cow Ghee",
        "Amul Pure Ghee 1L Pouch",
        "Aashirvaad Svasti Pure Cow Ghee Pouch",
        "Aashirvaad Svasti Cow Ghee Ceka Tetrapack",
        "Gowardhan Ghee",
        "Amul Pure Ghee 1L Tin",
        "Ananda Cow Ghee",
        "Aashirvaad Svasti Pure Cow Ghee",
        "Milkfood Rich Desi Danedar Ghee",
        "Mugdh Danedaar Desi Ghee",
        "BAROSi A2 Desi Cow Ghee Glass Jar",
        "Auric A2 Desi Cow Ghee | Vedic Bilona Method | Traditional Curd Churned",
        "Himalayan Natives A2 Badri cow ghee",
        "Himalayan Natives A2 Gir cow ghee",
        "Shree Radhey A2 Gir Cow Ghee",
        "Patanjali Cows Ghee Pet Jar",
        "Himalayan Natives Cow Ghee Original",
        "Two Brothers Organic Farms A2 Desi Gir Cow Cultured Ghee",
        "Ved A2 Premium Gir Cow Cultured Ghee",
        "Jivika Naturals Natural Cow Ghee",
        "Jivika Naturals Gir Cow Ghee",
        "Sid's Farm Cow Ghee",
        "Milkfood Pure Cow Ghee",
        "Mugdh Pure Cow Ghee Box",
        "Amul Cow Ghee",
        "Mother Dairy Ghee",
        "Gowardhan Cow Ghee Rt",
        "Himalayan Natives Pahadi Ghee",
        "Om Sweets & Snacks Desi Buffalo Ghee",
        "Amul Pasteurised Butter",
        "Amul Butter Chiplets",
        "Nutralite Doodhshakti Probiotic and Butter Spread",
        "Nutralite Doodhshakti Probiotic Butter Spread Tub",
        "Nutralite Activ Plant Based Buttery Spread",
        "Nutralite Premium Fat Spread Tub",
        "Amul Safed Makkhan/White Butter",
        "Amul Unsalted Butter",
        "Nutralite Doodhshakti Probiotic Butter Spread + Harvest Gold Milk Bread",
        "Shudh Garhwal Fresh Desi Makkhan",
        "Amul Garlic & Herbs Butter",
        "Amul Butter Unsalted Box",
        "Mother Dairy Pasteurized Table Butter",
        "Amul Delicious Margarine",
        "Amul Lite Milk Fat Bread Spread",
        "Delicious Delicious Fat Spread",
    ],
    
    // Function to get all products as a flat array
    getAllProducts: function() {
        return [
            ...this.rice,
            ...this.flour,
            ...this.bread,
            ...this.pasta,
            ...this.noodles,
            ...this.pulses,
            ...this.oils,
            ...this.ghee,
            // Add more categories here as needed
        ];
    }
}; 